version: '3.1'
services:
  stats-server:
    build: ./statistics-service/server
    image: stats-server_image
    container_name: stats-server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db-ewm
    - SPRING_DATASOURCE_USERNAME=stats_user
    - SPRING_DATASOURCE_PASSWORD=pass
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "6541:5432"
    volumes:
        - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-db-ewm
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=pass
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  ewm-service:
    build: ./ewm-main-service/
    image: main-service_image
    container_name: main-service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main-service-db-ewm
      - SPRING_DATASOURCE_USERNAME=main-service_user
      - SPRING_DATASOURCE_PASSWORD=pass
      - STATS_SERVER_URL=http://stats-server:9090
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  ewm-db:
    image: postgres:14-alpine
    container_name: main-service_db_container
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main-service-db-ewm
      - POSTGRES_USER=main-service_user
      - POSTGRES_PASSWORD=pass
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
